server_communication:
    resource: "@ServerCommunicationBundle/Controller/"
    type:     rest
    prefix:   /server
    options:
        expose: true

app:
    resource: "@AppBundle/Controller/"
    type:     rest
    options:
        expose: true

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"