server_comunication:
    resource: "@ServerComunicationBundle/Controller/"
    type:     annotation
    prefix:   /server

app:
    resource: "@AppBundle/Controller/"
    type:     rest
    options:
        expose: true

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"