# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    appbundle.util.inflector:
        class: AppBundle\Util\Inflector\NoopInflector

    appbundle.exception_subscriber:
        class: AppBundle\EventSubscriber\ServerCommunicationSubscriber
        arguments: ['@event_dispatcher', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_subscriber }